# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [2]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
array1d = np.array([1, 2, 3, 4, 5])

# Create a 2-dimensional NumPy array using np.array()
array2d = np.array([
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])

# Create a 3-dimensional Numpy array using np.array()
array3d = np. array([
    [
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]
    ],
    [
        [26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35]
    ]
])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [10]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array1d.ndim, array1d.dtype, array1d.size, array1d.shape

(1, dtype('int64'), 5, (5,))

In [11]:
# Attributes of 2-dimensional array
array2d.ndim, array2d.dtype, array2d.size, array2d.shape

(2, dtype('int64'), 10, (2, 5))

In [12]:
# Attributes of 3-dimensional array
array3d.ndim, array3d.dtype, array3d.size, array3d.shape

(3, dtype('int64'), 20, (2, 2, 5))

In [16]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
pd3d = pd.DataFrame(array2d)
pd3d

0   1   2   3   4
0   6   7   8   9  10
1  11  12  13  14  15

In [23]:
# Create an array of shape (10, 2) with only ones
array_ones = np.ones((10, 2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
# Create an array of shape (7, 2, 3) of only zeros
array_zeros = np.zeros((7, 2, 3))
array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
# Create an array within a range of 0 and 100 with step 3
array_step3 = np.arange(0, 100, 3)
array_step3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [26]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_random1 = np.random.uniform(low=0.0, high=10.0, size=(7 ,2))
array_random1

array([[3.7689478 , 8.33930425],
       [3.30250659, 4.24583407],
       [3.71395413, 3.13081091],
       [6.30303747, 7.45559429],
       [6.07165255, 0.75140539],
       [4.51096125, 8.96156298],
       [5.70462729, 9.74242815]])

In [27]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array_random2 = np.random.rand(3, 5)
array_random2

array([[0.86846248, 0.423512  , 0.64143069, 0.02933673, 0.42965906],
       [0.71409301, 0.95065253, 0.03204572, 0.5190893 , 0.49508503],
       [0.45623863, 0.04453064, 0.57283948, 0.50129084, 0.12390076]])

In [41]:
# Set the random seed to 42
random_seed = np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array_random3 = np.random.randint(11, size=(4, 6))
array_random3

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [53]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
array_random4 = np.random.randint(1, 12, (3, 7))

# Find the unique numbers in the array you just created
np.unique(array_random4)

array([ 1,  2,  3,  4,  6,  8,  9, 11])

In [54]:
# Find the 0'th index of the latest array you created
array_random4[0]

array([ 6,  8,  1,  8,  4, 11,  1])

In [55]:
# Get the first 2 rows of latest array you created
array_random4[:2]

array([[ 6,  8,  1,  8,  4, 11,  1],
       [ 8,  4,  6,  8,  4,  3,  9]])

In [63]:
# Get the first 2 values of the first 2 rows of the latest array
array_random4[:2, :2]

array([[6, 8],
       [8, 4]])

In [66]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array_random5 = np.random.randint(11, size=(3, 5))
array_ones = np.ones((3, 5))
array_random5, array_ones

(array([[ 6,  5,  5,  5,  2],
        [ 5,  7, 10, 10,  1],
        [ 4,  0,  0,  4,  2]]),
 array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [70]:
# Add the two arrays together
array1 = array_random5 + array_ones

In [71]:
# Create another array of ones of shape (5, 3)
array_ones1 = np.ones((5, 3))
array_ones1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
# Try add the array of ones and the other most recent array together
array1 + array_ones1

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [21]:
# Create another array of ones of shape (3, 5)


In [74]:
# Subtract the new array of ones from the other most recent array
array1 - array_ones

array([[ 6.,  5.,  5.,  5.,  2.],
       [ 5.,  7., 10., 10.,  1.],
       [ 4.,  0.,  0.,  4.,  2.]])

In [75]:
# Multiply the ones array with the latest array
array1 * array_ones

array([[ 7.,  6.,  6.,  6.,  3.],
       [ 6.,  8., 11., 11.,  2.],
       [ 5.,  1.,  1.,  5.,  3.]])

In [76]:
# Take the latest array to the power of 2 using '**'
array1 ** 2

array([[ 49.,  36.,  36.,  36.,   9.],
       [ 36.,  64., 121., 121.,   4.],
       [ 25.,   1.,   1.,  25.,   9.]])

In [77]:
# Do the same thing with np.square()
np.square(array1)

array([[ 49.,  36.,  36.,  36.,   9.],
       [ 36.,  64., 121., 121.,   4.],
       [ 25.,   1.,   1.,  25.,   9.]])

In [78]:
# Find the mean of the latest array using np.mean()
np.mean(array1)

np.float64(5.4)

In [79]:
# Find the maximum of the latest array using np.max()
np.max(array1)

np.float64(11.0)

In [80]:
# Find the minimum of the latest array using np.min()
np.min(array1)

np.float64(1.0)

In [81]:
# Find the standard deviation of the latest array
np.std(array1)

np.float64(3.0066592756745814)

In [82]:
# Find the variance of the latest array
np.var(array1)

np.float64(9.04)

In [87]:
# Reshape the latest array to (3, 5, 1)
np.reshape(array1, (3, 5, 1))

array([[[ 7.],
        [ 6.],
        [ 6.],
        [ 6.],
        [ 3.]],

       [[ 6.],
        [ 8.],
        [11.],
        [11.],
        [ 2.]],

       [[ 5.],
        [ 1.],
        [ 1.],
        [ 5.],
        [ 3.]]])

In [88]:
# Transpose the latest array
np.transpose(array1)

array([[ 7.,  6.,  5.],
       [ 6.,  8.,  1.],
       [ 6., 11.,  1.],
       [ 6., 11.,  5.],
       [ 3.,  2.,  3.]])

What does the transpose do?

In [90]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array_random11 = np.random.randint(11, size=(3, 3))
array_random12 = np.random.randint(11, size=(3, 2))
array_random11, array_random12

(array([[3, 2, 0],
        [0, 4, 5],
        [2, 8, 4]]),
 array([[7, 0],
        [4, 2],
        [0, 3]]))

In [92]:
# Perform a dot product on the two newest arrays you created
array_random11 @ array_random12, np.dot(array_random11, array_random12)

(array([[29,  4],
        [16, 23],
        [46, 28]]),
 array([[29,  4],
        [16, 23],
        [46, 28]]))

In [110]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array_random13 = np.random.randint(11, size=(4, 3))
array_random14 = np.random.randint(11, size=(4, 3))

In [97]:
# Perform a dot product on the two newest arrays you created
array_random13 @ array_random14

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

It doesn't work. How would you fix it?

In [98]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
array_random13 @ array_random14.T

array([[ 34,  64,  58,  28],
       [ 55,  84,  11,  78],
       [ 88, 140,  54, 135],
       [ 79, 135,  65,  70]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [101]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_random13, array_random14

(array([[4, 6, 0],
        [2, 1, 8],
        [9, 5, 9],
        [2, 7, 7]]),
 array([[ 1,  5,  6],
        [ 1, 10,  9],
        [ 1,  9,  0],
        [ 7,  0,  8]]))

In [99]:
# Compare the two arrays with '>'
array_random13 > array_random14

array([[ True,  True, False],
       [ True, False, False],
       [ True, False,  True],
       [False,  True, False]])

What happens when you compare the arrays with `>`?

In [100]:
# Compare the two arrays with '>='
array_random13 >= array_random14

array([[ True,  True, False],
       [ True, False, False],
       [ True, False,  True],
       [False,  True, False]])

In [102]:
# Find which elements of the first array are greater than 7
array_random13 > 7

array([[False, False, False],
       [False, False,  True],
       [ True, False,  True],
       [False, False, False]])

In [103]:
# Which parts of each array are equal? (try using '==')
array_random13 == array_random14

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [125]:
# Sort one of the arrays you just created in ascending order
array_seed = np.random.seed(1)
array_random15 = np.random.randint(11, size=(4, 3))
print(array_random15)
np.sort(array_random15)

[[5 8 9]
 [5 0 0]
 [1 7 6]
 [9 2 4]]


array([[5, 8, 9],
       [0, 0, 5],
       [1, 6, 7],
       [2, 4, 9]])

In [126]:
# Sort the indexes of one of the arrays you just created
np.argsort(array_random15)

array([[0, 1, 2],
       [1, 2, 0],
       [0, 2, 1],
       [1, 2, 0]])

In [131]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array_random15)

np.int64(2)

In [132]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array_random15)

np.int64(4)

In [133]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array_random15, axis=1)

array([2, 0, 1, 0])

In [134]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array_random15, axis=0)

array([2, 1, 1])

In [136]:
# Create an array of normally distributed random numbers
np.random.normal(5, 3, (3, 6))

array([[7.70256785, 2.94881642, 4.63132932, 2.1926917 , 4.19633576,
        6.5910664 ],
       [2.92501774, 3.80973942, 2.9384819 , 2.46438308, 2.98626161,
        4.9620062 ],
       [1.64806895, 5.70324709, 9.97940653, 7.22613248, 4.42449334,
        2.33711311]])

In [143]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.